version: '3.8'
services:

  academi-seed-server-1:
    image: 'sever3d/blockchainseedserver'
    ports:
    - '3030:3030'
    restart: always
    environment:
      - PROFILE=dev
      - SEEDSERVERS_LIST=http://academi-seed-server-1:3030,http://academi-seed-server-2:3030
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:3030/healthcheck"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  academi-seed-server-2:
    image: 'sever3d/blockchainseedserver'
    ports:
    - '3040:3030'
    restart: always
    environment:
      - PROFILE=dev
      - SEEDSERVERS_LIST=http://academi-seed-server-1:3030,http://academi-seed-server-2:3030
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:3030/healthcheck"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  academi-sevchain-1:
    image: 'sever3d/blockchain:latest'
    ports:
    - '3001:3001'
    - '5001:5001'
    restart: always
    environment:
      - SEEDSERVERS_LIST=http://academi-seed-server-1:3030,http://academi-seed-server-2:3030
      - PROFILE=dev
      - PEERS=ws://academi-sevchain-2:5002
    depends_on:
      academi-seed-server-1:
        condition: service_healthy
      academi-seed-server-2:
        condition: service_healthy

  academi-sevchain-2:
    image: 'sever3d/blockchain:latest'
    ports:
    - '3002:3001'
    - '5002:5001'
    restart: always
    environment:
      - SEEDSERVERS_LIST=http://academi-seed-server-1:3030,http://academi-seed-server-2:3030
      - PROFILE=dev
      - PEERS=ws://academi-sevchain-1:5001
    depends_on:
      academi-seed-server-1:
        condition: service_healthy
      academi-seed-server-2:
        condition: service_healthy