x-healthcheck-settings: &healthcheck-settings
  interval: 10s
  retries: 10
  start_period: 15s
  timeout: 5s

x-db-env-conf: &db-env
  POSTGRESDB: ${POSTGRESDB}
  DATABASE_USERNAME: ${PSQL_USER}
  DATABASE_PASSWORD: ${PSQL_PASSWORD}
  DATABASE_ENDPOINT: postgres
  DATABASE_PORT: 5432

x-db-schema-creation: &db-schema-creation
  image: quay.io/ukhomeofficedigital/postgres:latest
  volumes:
    - ./sql:/sql
  environment:
    <<: *db-env
  entrypoint: ["/sql/create-schema.sh"]
  depends_on:
    postgres:
      condition: service_healthy
  networks:
    - msc

services:
  postgres:
    image: postgres:13.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRESPASSWORD}
      - POSTGRES_USER=${POSTGRESUSER}
      - POSTGRES_DB=${POSTGRESDB}
    networks:
      - msc
    healthcheck:
      test: ["CMD", "psql", "-U", "${POSTGRESUSER}", "-d", "${POSTGRESDB}"]
      interval: 500ms
      timeout: 1s
      retries: 5
    volumes:
      - dbdata:/var/lib/postgresql/data


  # Create DB schemas
  students-schema-creation:
    <<: *db-schema-creation
    command: ["users"]

  items-schema-creation:
    <<: *db-schema-creation
    command: ["items"]

  uilogs-schema-creation:
    <<: *db-schema-creation
    command: ["uilogs"]

  core-schema-creation:
    <<: *db-schema-creation
    command: ["core"]

  # Core services


    

volumes:
  dbdata:
    driver: local

networks:
  msc:
    driver: bridge